package fpga_components
{

import Chisel._
import scala.math._

object LutConstants { 
    // LUT CONFIG
    var VAR_NUM_INPUTS_PER_LUT = 4
    var VAR_NUM_OUTPUTS_PER_LUT = 1
    var VAR_NUM_CONFIGS_PER_LUT = 16
    var VAR_NUM_MUXES_PER_LUT = 1
    // CLB CONFIG
    var VAR_NUM_CLB_IN = 16
    var VAR_NUM_CLB_OUT = 4
    var VAR_NUM_LUTS_PER_CLB = 4
    var VAR_NUM_CLB_LUT_CONFIGS = 64
    var VAR_NUM_CLB_MUX_CONFIGS = 4
    var VAR_TOTAL_MUX_CONFIGS = 4
    var VAR_NUM_IPIN_PER_TILE = 11
    var VAR_NUM_OPIN_PER_TILE = 4
    var VAR_NUM_XBAR_INPUTS = 15
    var VAR_NUM_XBAR_OUTPUTS = 16
    var VAR_NUM_XBAR_PER_MUX_CONFIGS = 4
    var VAR_NUM_XBAR_CONFIGS = 64
    var VAR_TOTAL_XBAR_CONFIGS = 64
    var VAR_IPIN_INPUT_WIDTH = 4
    var VAR_IPIN_CONFIG_WIDTH = 2
    var VAR_NUM_CHANXY_PER_TILE = 20
    var TOTAL_CHANXY_IN = 196
    var VAR_CHANXY_INPUT_WIDTH_ARR = Array(10,10,10,10,9,10,10,10,10,9,10,10,10,10,9,10,10,10,10,9)
    var VAR_CHANXY_CONFIG_WIDTH_ARR = Array(4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4)
    var VAR_CHANXY_INPUT_START_ARR = Array(0,10,20,30,40,49,59,69,79,89,98,108,118,128,138,147,157,167,177,187)
    var VAR_CHANXY_CONFIG_START_ARR = Array(0,4,8,12,16,20,24,28,32,36,40,44,48,52,56,60,64,68,72,76)
    var VAR_LUT_CONFIGS_START = 0
    var VAR_LUT_CONFIGS_END = VAR_LUT_CONFIGS_START + VAR_NUM_CLB_LUT_CONFIGS - 1
    var VAR_MUX_CONFIGS_START = VAR_NUM_CLB_LUT_CONFIGS
    var VAR_MUX_CONFIGS_END = VAR_MUX_CONFIGS_START + VAR_TOTAL_MUX_CONFIGS - 1
    var VAR_XBAR_CONFIGS_START = VAR_MUX_CONFIGS_END + 1
    var VAR_XBAR_CONFIGS_END = VAR_XBAR_CONFIGS_START + VAR_TOTAL_XBAR_CONFIGS - 1
    var VAR_TOTAL_IPIN_CONFIGS = 22
    var VAR_SBCB_IPIN_CONFIGS_START = VAR_XBAR_CONFIGS_END + 1
    var VAR_SBCB_IPIN_CONFIGS_END = VAR_SBCB_IPIN_CONFIGS_START + VAR_TOTAL_IPIN_CONFIGS - 1
    var VAR_TOTAL_CHANXY_CONFIGS = 80
    var VAR_SBCB_CHANXY_CONFIGS_START = VAR_SBCB_IPIN_CONFIGS_END + 1
    var VAR_SBCB_CHANXY_CONFIGS_END = VAR_SBCB_CHANXY_CONFIGS_START + VAR_TOTAL_CHANXY_CONFIGS - 1
    var VAR_TOTAL_NUM_CONFIGS = VAR_SBCB_CHANXY_CONFIGS_END + 1
    var VAR_CONFIGS_FILE_DEPTH = 1 + (VAR_TOTAL_NUM_CONFIGS/32)
}

}

