asm_test_timeout=10000
bmark_timeout=500000

local_asm_tests += \

# put these back in if you wish to 
# practice writing micro-code for these
# instructions...
#	riscv-vu_addm \
	riscv-vu_movn \
	riscv-vu_strcpy \

include ../common/Makefile.include
